source "$HOME/_conf/shell/var_env.sh"

#Color
autoload -U colors && colors

PATH=$HOME/.brew/bin:$_CONF_DIR/script:$PATH
HISTFILE=~/.zshrc_history
SAVEHIST=5000
HISTSIZE=5000

setopt inc_append_history
setopt share_history

##ALIAS
alias so="source $_CONF_DIR/zshrc"
source "$_CONF_DIR/shell/alias.sh"

##FUNCTIONS
source "$_CONF_DIR/shell/function/ll.sh"
source "$_CONF_DIR/shell/function/lla.sh"
source "$_CONF_DIR/shell/function/man.sh"
source "$_CONF_DIR/shell/function/precmd.sh"
source "$_CONF_DIR/shell/function/save-go.sh"

##mmv *.txt *.data
autoload -U zmv
alias mmv='noglob zmv -W'


export NVM_DIR="/home/gaut/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
