# env var
export _CONF_DIR="$HOME/_conf"
export _GIT_DIR="$HOME/_git"
export _VIM_DIR="$_CONF_DIR/oblovim"

##COMPLETION
autoload -U compinit
compinit

##HISTORY
export PATH="$PATH:$HOME:/home/gaut/.local/bin"
export PYTHONPATH="$CONF_DIR/python"
export PFDC="172.31.8.109"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# virtual_env
# export WORKON_HOME="$HOME/Envs"
# source /usr/local/bin/virtualenvwrapper.sh


# history
setopt inc_append_history
setopt share_history

# color
autoload -U colors && colors


##ALIAS
alias so="source $_CONF_DIR/zshrc"
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias conf="cd $_CONF_DIR"
alias meteo='curl wttr.in'
alias vimsess="vim -S .session.vim"
alias dc="docker-compose"
alias dcup="docker-compose up"
alias dcdb="docker-compose exec db bash"
alias dcback="docker-compose exec back bash"
alias dcfront="docker-compose exec front bash"

#mmv *.txt *.data
autoload -U zmv
alias mmv='noglob zmv -W'


##FUNCTIONS
source "$_CONF_DIR/shell/function/ll.sh"
source "$_CONF_DIR/shell/function/lla.sh"
source "$_CONF_DIR/shell/function/man.sh"
source "$_CONF_DIR/shell/function/precmd.sh"
source "$_CONF_DIR/shell/function/save-go.sh"
export LESS=-RFX


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/gauthiergilabert/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/gauthiergilabert/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/gauthiergilabert/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/gauthiergilabert/google-cloud-sdk/completion.zsh.inc'; fi
