
call pathogen#infect()
call pathogen#helptags()
"let NERDTreeShowHidden=1

" Map <S-n> :NERDTreeToggle<CR>

set tabstop=4
set autoindent
set number
syntax on
set list
set listchars=tab:\|\ 
set mouse=a

""set colorcolumn=80
" au BufWinEnter * let w:m1=matchadd('ErrorMsg', '\%=80v.\+', -1)

ab main int<TAB>main(void ac, void av)<CR>{<CR><TAB>(void)ac;<CR>(void)av;<CR><CR>return (0);<CR><BACKSPACE>}<CR><ESC><UP><UP><UP>

" emmet
map <Tab> <c-y>,i

" Multiscreen
noremap <C-k> <Esc><C-w>k
noremap <C-j> <Esc><C-w>j
noremap <C-h> <Esc><C-w>h
noremap <C-l> <Esc><C-w>l
noremap <S-v> <C-W>v
noremap <S-s> <C-W>s
noremap <S-c> <C-W>c

let mapleader = ","

" Print
map <S-H> 0
map <S-L> $
map <leader>str<CR> oft_putstr("");<ESC>F"
map <leader>nl<CR> ,str<CR>i\n<ESC>
map <leader>nbr<CR> oft_putnbr();<ESC>F(
map <leader>slim<CR> ,str<CR>i----------------------<ESC>
map <leader>dnbr<CR> byek,nbr<CR>p<ESC>k,str<CR>hpf"i : <ESC>k
map <leader>dstr<CR> bye,str<CR>pk,str<CR>pf"i : <ESC>k

" \""(){}<>
noremap <leader>" viw<ESC>a"<ESC>hbi"<ESC>lel
noremap <leader>( viw<ESC>a)<ESC>hbi(<ESC>lel
noremap <leader>[ viw<ESC>a]<ESC>hbi[<ESC>lel
noremap <leader>< viw<ESC>a><ESC>hbi<<ESC>lel


map <S-t> :Tagbar<CR>

map ,vrc <ESC>:w<CR>:source vimrc<CR>
inoremap jk <ESC>
inoremap kj <ESC>

" useless keys
map <ESC> <NOP>
map <UP> <NOP>
map <DOWN> <NOP>
map <LEFT> <NOP>
map <RIGHT> <NOP>
map! <ESC> <NOP>
map! <UP> <NOP>
map! <DOWN> <NOP>
map! <LEFT> <NOP>
map! <RIGHT> <NOP>

"insert ctype
noremap <leader>ti 0i<TAB>int<TAB>;<ESC>i
noremap <leader>tv 0i<TAB>void<TAB>;<ESC>i
noremap <leader>tc 0i<TAB>char<TAB>;<ESC>i
noremap <leader>td 0i<TAB>double<TAB>;<ESC>i
